# Generated by Django 2.2.1 on 2019-08-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_description',
            field=models.CharField(default='qq', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=6),
            preserve_default=False,
        ),
    ]
